import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: [
    "typescript"
  ],
  options: {
    typeAware: true,
  },
  categories: {
    correctness: "off"
  },
  env: {
    builtin: true
  },
  rules: {
    "constructor-super": "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": ["error"],
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-unassigned-vars": "error",
    "no-unexpected-multiline": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": ["error"],
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "preserve-caught-error": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "curly": "error",
    "eqeqeq": "error",
    "guard-for-in": "error",
    "max-classes-per-file": "error",
    "no-bitwise": "error",
    "no-caller": "error",
    "no-eval": "error",
    "no-labels": "error",
    "no-new-wrappers": "error",
    "no-throw-literal": "error",
    "no-var": "error",
    "prefer-const": "error",
    "typescript/no-explicit-any": "error",
  },
  overrides: [
    {
      files: [
        "**/*.{ts,tsx}"
      ],
      rules: {
        "solid/jsx-no-duplicate-props": "error",
        "solid/jsx-no-undef": ["error", { typescriptEnabled: true }],
        "solid/jsx-uses-vars": "error",
        "solid/no-unknown-namespaces": "off",
        "solid/no-innerhtml": "error",
        "solid/jsx-no-script-url": "error",
        "solid/components-return-once": "warn",
        "solid/no-destructure": "error",
        "solid/prefer-for": "error",
        "solid/reactivity": "warn",
        "solid/event-handlers": "warn",
        "solid/imports": "warn",
        "solid/style-prop": "warn",
        "solid/no-react-deps": "warn",
        "solid/no-react-specific-props": "warn",
        "solid/self-closing-comp": "warn",
        "solid/no-array-handlers": "off",
        "solid/prefer-show": "off",
        "solid/no-proxy-apis": "off",
        "solid/prefer-classlist": "off",
      },
      jsPlugins: [
        "eslint-plugin-solid"
      ],
      globals: {
        __dirname: "off",
        __filename: "off",
        Buffer: "off",
        clearImmediate: "off",
        exports: "off",
        global: "off",
        module: "off",
        process: "off",
        require: "off",
        setImmediate: "off",
        FilePickerAcceptType: "readonly", // wicg-file-system-access
      },
      env: {
        browser: true,
        jest: true
      }
    }
  ]
});