//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JA_Tennis.Assets.Resources.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JA_Tennis.Assets.Resources.Model.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifié entrant impossible à enlever.
        /// </summary>
        public static string IDS_ERR_DEENTRANT_LOC {
            get {
                return ResourceManager.GetString("IDS_ERR_DEENTRANT_LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déprogrammation du joueur impossible, match joué.
        /// </summary>
        public static string IDS_ERR_DEPROGRAM_LOC {
            get {
                return ResourceManager.GetString("IDS_ERR_DEPROGRAM_LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifié sortant non supprimable, match joué.
        /// </summary>
        public static string IDS_ERR_DESORTANT_LOC {
            get {
                return ResourceManager.GetString("IDS_ERR_DESORTANT_LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifié sortant non supprimable, tableau suivant verrouillé.
        /// </summary>
        public static string IDS_ERR_DESORTANT_SUIV_LOC {
            get {
                return ResourceManager.GetString("IDS_ERR_DESORTANT_SUIV_LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmation du joueur impossible, match joué.
        /// </summary>
        public static string IDS_ERR_PROGAM_LOC {
            get {
                return ResourceManager.GetString("IDS_ERR_PROGAM_LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifié sortant en position invalide, boite cachée.
        /// </summary>
        public static string IDS_ERR_SORTANT_HIDE {
            get {
                return ResourceManager.GetString("IDS_ERR_SORTANT_HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de qualifier une tête de série ou un qualifié entrant.
        /// </summary>
        public static string IDS_ERR_SORTANT_TDS_E {
            get {
                return ResourceManager.GetString("IDS_ERR_SORTANT_TDS_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification impossible devant un qualifié entrant.
        /// </summary>
        public static string IDS_ERR_TAB_ENTRANT_DEVANT {
            get {
                return ResourceManager.GetString("IDS_ERR_TAB_ENTRANT_DEVANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecrasement du qualifié entrant impossible.
        /// </summary>
        public static string IDS_ERR_TAB_ENTRANT_LOC {
            get {
                return ResourceManager.GetString("IDS_ERR_TAB_ENTRANT_LOC", resourceCulture);
            }
        }
    }
}
